### ISSUE TITLE
Connection pool min-idle warm up with apache common pool

### ISSUE THREAD

**Issue by morenice** [lettuce-io/lettuce-core#1814]
I have a problem performance issue. So I prepared setShareNativeConnection and connection pool settings.
But it is not prepared as many as the connections of min-idle during application startup.
How can I make the number of connections min-idle application startup?

**connection pool setting of spring boot application.yaml**
```
spring:
  redis:
      host: XXXXX.com
      port: 6379
      password: null
      lettuce:
        pool:
          min-idle: 20
          max-active: 50
          max-idle: 50
        shutdown-timeout: 1000ms
        shutdown-timeout-long: 1000
```

**setShareNativeConnection setting**
```
        @Bean
	public RedisConnectionFactory redisConnectionFactory() {
		RedisStandaloneConfiguration redisConf = new RedisStandaloneConfiguration();
		redisConf.setHostName(host);
		redisConf.setPort(port);
		if (StringUtils.isNotEmpty(password)) {
			redisConf.setPassword(RedisPassword.of(password));
		}

		GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
		poolConfig.setMaxIdle(maxIdle);
		poolConfig.setMinIdle(minIdle);
		poolConfig.setMaxTotal(maxActive);

		LettuceClientConfiguration clientConfig = LettucePoolingClientConfiguration.builder()
			.poolConfig(poolConfig)
			.shutdownTimeout(Duration.ofMillis(shutdownTimeoutDuration))
			.build();

		var connectionFactory = new LettuceConnectionFactory(redisConf, clientConfig);
		connectionFactory.setShareNativeConnection(false);
		return connectionFactory;
	}
```

$ lsof -nPi | grep 6379
```
java      35522 morenice  229u  IPv6 0xff47c98ad989b529      0t0  TCP 127.0.0.1:52439->127.0.0.1:6379 (ESTABLISHED)
redis-ser 35907 morenice    4u  IPv4 0xff47c98af0d2d5c1      0t0  TCP 127.0.0.1:6379 (LISTEN)
redis-ser 35907 morenice    5u  IPv4 0xff47c98ae8afa099      0t0  TCP 127.0.0.1:6379->127.0.0.1:52439 (ESTABLISHED)
```
